// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Categories derived from a mod's contents. Each list is de-duplicated and
 * sorted. Champions hold display names (e.g. `"Aatrox"`); maps and tags hold
 * well-known slugs (e.g. `"summoners-rift"`, `"champion-skin"`).
 */
export type DerivedCategorization = {
  champions: Array<string>;
  maps: Array<string>;
  tags: Array<string>;
};
