// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One library mod flagged by the pre-patch linked-bin check, sent in [`LinkedBinReport`].
 */
export type LinkedBinOffenderInfo = {
  /**
   * Library mod id (matches `InstalledMod.id` on the frontend).
   */
  modId: string;
  /**
   * Mod display name — a fallback for the UI when it can't resolve the id.
   */
  displayName: string;
  /**
   * WAD targets (e.g. `Ahri.wad.client`) in this mod that contain the unresolved
   * bins. May be empty when the offending bin came from a RAW override.
   */
  wads: Array<string>;
  /**
   * The missing linked bin paths, deduped.
   */
  missingLinks: Array<string>;
};
