// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkedBinOffenderInfo } from "./LinkedBinOffenderInfo";

/**
 * Result of [`check_linked_bins`]: enabled mods whose property-bins reference linked
 * dependencies that won't resolve at load time. Empty `offenders` means clean.
 */
export type LinkedBinReport = { offenders: Array<LinkedBinOffenderInfo> };
