// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatcherPreflight = {
  compatible: boolean;
  backend: string;
  architecture: string;
  signature: string | null;
  reason: string | null;
};
