// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatcherPhase } from "./PatcherPhase";

export type PatcherStatus = {
  running: boolean;
  configPath: string | null;
  phase: PatcherPhase;
  backend: string | null;
  message: string | null;
};
