// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatcherConfig = {
  logFile?: string;
  timeoutMs?: number;
  flags?: number;
  workshopProjects?: Array<string>;
};
