// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatcherAvailability = {
  supported: boolean;
  ready: boolean;
  reason: string | null;
  requiresSetup: boolean;
  permissionRequired: boolean;
  helperVersion: string | null;
};
