// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HotkeyAvailability } from "./HotkeyAvailability";
import type { PatcherAvailability } from "./PatcherAvailability";

export type PlatformSupport = {
  os: string;
  architecture: string;
  patcher: PatcherAvailability;
  hotkeys: HotkeyAvailability;
};
