// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One archive that failed the integrity scan, sent in [`WadScanFailedPayload`].
 *
 * Retained for the `patcher-wad-scan-failed` event contract and its generated
 * TypeScript binding. The scan itself runs inside the Windows injection host,
 * which the macOS-focused fork does not use, so this is currently only emitted
 * on Windows builds wired to that host.
 */
export type WadScanFailureInfo = {
  /**
   * The offending archive (e.g. `TahmKench.wad.client`), if its name parsed.
   */
  wad: string | null;
  /**
   * The NTSTATUS-style code the scan reported (e.g. `c0000229` skinhack,
   * `c000003e` corrupt WAD).
   */
  status: string;
};
