// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WadScanFailureInfo } from "./WadScanFailureInfo";

/**
 * Payload for the `patcher-wad-scan-failed` event, emitted when the injected
 * DLL's integrity scan rejects one or more modded archives.
 */
export type WadScanFailedPayload = {
  /**
   * The archives that failed the scan, de-duplicated. May be empty if no
   * names could be parsed from the scan log.
   */
  failures: Array<WadScanFailureInfo>;
};
